# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99121342a942045a82d351dba2be594cbb9ade250a7c2a22a36b3b6b469e3a816920df68634da8489855bbe308b1d2df5e696949d8a8d24c1d62c7dbfd5e8232

test:
  secret_key_base: 916ada6b09cd7dfa2c9b70a162b2bdf311788cd6e1e670994b1c12e505368e77539b2ed03e15a59a9b403cba22d79a2813c007f82eb2d123ccfc674874bfcba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
